// Created by iWeb 3.0.4 local-build-20140107

function writeMovie1()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id3" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="518" height="275" style="height: 275px; left: 177px; position: absolute; top: 1535px; width: 518px; z-index: 1; "><param name="src" value="Media/faultRuptureSlower-1.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id3" type="video/quicktime" width="518" height="275" style="height: 275px; left: 177px; position: absolute; top: 1535px; width: 518px; z-index: 1; "><param name="src" value="Seattle_Landslides_files/faultRuptureSlower.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/faultRuptureSlower-1.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id3" type="video/quicktime" width="518" height="275" data="Media/faultRuptureSlower-1.mov" style="height: 275px; left: 177px; position: absolute; top: 1535px; width: 518px; z-index: 1; "><param name="src" value="Media/faultRuptureSlower-1.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-5,5,10,133),url:'Seattle_Landslides_files/stroke_8.png'},{rect:new IWRect(-5,-5,10,10),url:'Seattle_Landslides_files/stroke_9.png'},{rect:new IWRect(5,-5,373,10),url:'Seattle_Landslides_files/stroke_10.png'},{rect:new IWRect(378,-5,10,10),url:'Seattle_Landslides_files/stroke_11.png'},{rect:new IWRect(378,5,10,133),url:'Seattle_Landslides_files/stroke_12.png'},{rect:new IWRect(378,138,10,10),url:'Seattle_Landslides_files/stroke_13.png'},{rect:new IWRect(5,138,373,10),url:'Seattle_Landslides_files/stroke_14.png'},{rect:new IWRect(-5,138,10,10),url:'Seattle_Landslides_files/stroke_15.png'}],new IWSize(383,143)),stroke_2:new IWEmptyStroke(),stroke_0:new IWStrokeParts([{rect:new IWRect(-5,5,10,375),url:'Seattle_Landslides_files/stroke.png'},{rect:new IWRect(-5,-5,10,10),url:'Seattle_Landslides_files/stroke_1.png'},{rect:new IWRect(5,-5,208,10),url:'Seattle_Landslides_files/stroke_2.png'},{rect:new IWRect(213,-5,11,10),url:'Seattle_Landslides_files/stroke_3.png'},{rect:new IWRect(213,5,11,375),url:'Seattle_Landslides_files/stroke_4.png'},{rect:new IWRect(213,380,11,10),url:'Seattle_Landslides_files/stroke_5.png'},{rect:new IWRect(5,380,208,10),url:'Seattle_Landslides_files/stroke_6.png'},{rect:new IWRect(-5,380,10,10),url:'Seattle_Landslides_files/stroke_7.png'}],new IWSize(218,385))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Seattle_Landslides_files/Seattle_LandslidesMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');adjustLineHeightIfTooBig('id21');adjustFontSizeIfTooBig('id21');adjustLineHeightIfTooBig('id22');adjustFontSizeIfTooBig('id22');adjustLineHeightIfTooBig('id23');adjustFontSizeIfTooBig('id23');adjustLineHeightIfTooBig('id24');adjustFontSizeIfTooBig('id24');adjustLineHeightIfTooBig('id25');adjustFontSizeIfTooBig('id25');adjustLineHeightIfTooBig('id26');adjustFontSizeIfTooBig('id26');adjustLineHeightIfTooBig('id27');adjustFontSizeIfTooBig('id27');adjustLineHeightIfTooBig('id28');adjustFontSizeIfTooBig('id28');adjustLineHeightIfTooBig('id29');adjustFontSizeIfTooBig('id29');adjustLineHeightIfTooBig('id30');adjustFontSizeIfTooBig('id30');adjustLineHeightIfTooBig('id31');adjustFontSizeIfTooBig('id31');adjustLineHeightIfTooBig('id32');adjustFontSizeIfTooBig('id32');adjustLineHeightIfTooBig('id33');adjustFontSizeIfTooBig('id33');adjustLineHeightIfTooBig('id34');adjustFontSizeIfTooBig('id34');adjustLineHeightIfTooBig('id35');adjustFontSizeIfTooBig('id35');adjustLineHeightIfTooBig('id36');adjustFontSizeIfTooBig('id36');adjustLineHeightIfTooBig('id37');adjustFontSizeIfTooBig('id37');adjustLineHeightIfTooBig('id38');adjustFontSizeIfTooBig('id38');adjustLineHeightIfTooBig('id39');adjustFontSizeIfTooBig('id39');adjustLineHeightIfTooBig('id40');adjustFontSizeIfTooBig('id40');adjustLineHeightIfTooBig('id41');adjustFontSizeIfTooBig('id41');adjustLineHeightIfTooBig('id42');adjustFontSizeIfTooBig('id42');adjustLineHeightIfTooBig('id43');adjustFontSizeIfTooBig('id43');adjustLineHeightIfTooBig('id44');adjustFontSizeIfTooBig('id44');adjustLineHeightIfTooBig('id45');adjustFontSizeIfTooBig('id45');adjustLineHeightIfTooBig('id46');adjustFontSizeIfTooBig('id46');adjustLineHeightIfTooBig('id47');adjustFontSizeIfTooBig('id47');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
